import { chromium } from 'playwright';
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
page.on('console', msg => console.log('BROWSER:', msg.type(), msg.text()));
page.on('pageerror', err => console.log('PAGEERROR:', err.message));
page.on('requestfailed', req => console.log('REQUESTFAILED:', req.url(), req.failure()?.errorText));
await page.goto('http://127.0.0.1:8000/index.html', { waitUntil: 'domcontentloaded', timeout: 60000 });
await page.waitForTimeout(6000);
console.log('TITLE:', await page.title());
console.log('CANVAS_COUNT:', await page.locator('canvas').count());
console.log('LOADING_TEXT:', await page.locator('#loading').textContent().catch(() => ''));
console.log('BODY_TEXT:', (await page.locator('body').innerText()).slice(0, 1200));
await browser.close();
