from abc import ABC, abstractmethod
from typing import Optional, List
from app.domain.models.entities import Task, User

class TaskRepositoryPort(ABC):
    @abstractmethod
    async def get_by_sdamgia_id(self, sdamgia_id: str) -> Optional[Task]: ...
    @abstractmethod
    async def create_task(self, **kwargs) -> Task: ...
    @abstractmethod
    async def get_by_id(self, task_id: int) -> Optional[Task]: ...

class UserRepositoryPort(ABC):
    @abstractmethod
    async def get_by_username(self, username: str) -> Optional[User]: ...
    @abstractmethod
    async def create_user(self, username: str) -> User: ...
    @abstractmethod
    async def get_by_id(self, user_id: int) -> Optional[User]: ...